name: CI

on: push

jobs:
  hello:
    name: Hello
    runs-on: self-hosted
    steps:
      - run: echo Hi
      - uses: azure/setup-kubectl@v2.0
      - run: kubectl version
      - run: kubectl cluster-info